#ifndef SPRITES_TILES_H_
#define SPRITES_TILES_H_

#include <nds.h>

#define SPRITE_OFFSET 50

u8 player_1_tile_0[64] = {
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET
};

u8 player_1_tile_1[64] = {
		1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET
};

u8 player_1_tile_2[64] = {
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET
};

u8 player_1_tile_3[64] = {
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 4 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 1 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET
};

u8 player_2_tile_0[64] = {
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET
};

u8 player_2_tile_1[64] = {
		2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET
};

u8 player_2_tile_2[64] = {
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET,
		0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET
};

u8 player_2_tile_3[64] = {
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 3 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET,
		2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 2 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET, 0 + SPRITE_OFFSET
};

#endif /* SPRITES_TILES_H_ */
